### ISSUE TITLE
Test Cases broken on governance branch

### ISSUE THREAD

**Issue by nervehammer** [support-somish/NexusMutual#54]
New changes introduced in **governance branch** breaks a lot of test cases.

**Comment by tech-somish** [comment]
All existing test cases are fixed.
go through commit No. e513917f02d8ab13c13a2e2a94823f22b1eabf89

**Comment by nervehammer** [comment]
@tech-somish test working fine, but coverage is still broken :(

**Comment by nervehammer** [comment]
Seems Travis build was not initiated well I have manually tested the new changes.
